name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:

  docker:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        arch: [linux/amd64, linux/arm64]
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.2.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.6.1
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-build-x-${{ matrix.arch }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-x-${{ matrix.arch }}-
      - name: Build
        uses: docker/build-push-action@v6.8.0
        with:
          platforms: ${{ matrix.arch }}
          push: false
          load: true
          tags: oittaa/firebase:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      -
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      - name: Smoke test
        run: docker run --rm oittaa/firebase --version

  publish:
    if: ${{ github.event_name == 'push' }}
    needs: docker
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set Firebase version
        run: echo "::set-output name=VERSION::$(grep -oP '^ARG VERSION=\K.*' Dockerfile)"
        id: firebase-tools
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.2.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.6.1
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-build-x-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-x-
      - name: Login to DockerHub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6.8.0
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            oittaa/firebase:latest
            oittaa/firebase:${{ steps.firebase-tools.outputs.VERSION }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
