name: Nightly Test

# Run the nightly tests at at 6 AM UTC
on:
  schedule:
    - cron: "0 6 * * *"
jobs:

  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.2.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1
      - name: Build
        uses: docker/build-push-action@v6.9.0
        with:
          platforms: linux/amd64,linux/arm64
          push: false
          load: false
          tags: oittaa/firebase:latest

  update:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Update Firebase CLI version
        run: ./update-version.sh
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          delete-branch: true
          title: 'Update Firebase CLI by create-pull-request action'
